export const teams = [
  {
    id: "manchester-city",
    name: "Manchester City",
    league: "Premier League",
    transferBudget: "£200M",
    wageBudget: "£3.5M / week",
    facilities: "State of the Art",
    expectations: "Win Everything",
    difficulty: "Medium",
    description:
      "One of the richest clubs in the world with a star-studded squad. Expectations are extremely high, but you have the resources to succeed.",
    strengths: [
      "Enormous transfer budget",
      "World-class players in every position",
      "Excellent training facilities",
      "Strong youth recruitment",
    ],
    weaknesses: [
      "Extremely high board expectations",
      "Pressure to win multiple trophies",
      "Aging players in key positions",
    ],
    opportunities: [
      "Potential to dominate domestically and in Europe",
      "Attract any player in the world",
      "Build a dynasty for years to come",
    ],
    threats: [
      "Competition from other elite Premier League clubs",
      "Financial Fair Play regulations",
      "High expectations can lead to quick dismissal",
    ],
    tactics: [
      {
        name: "Guardiola's Positional Play",
        description: "A possession-based approach focusing on positional superiority and creating overloads.",
        formation: "4-3-3 DM Wide",
        instructions: ["Higher Defensive Line", "Shorter Passing", "Work Ball Into Box", "Counter-Press"],
      },
      {
        name: "Direct Counter-Attack",
        description: "Absorb pressure and strike quickly on the break using pace in wide areas.",
        formation: "4-2-3-1 Wide",
        instructions: ["Counter", "More Direct Passing", "Higher Tempo", "Be More Disciplined"],
      },
    ],
    youthAcademy: {
      overview:
        "Manchester City boasts one of the best youth setups in world football, with state-of-the-art facilities and excellent coaching staff.",
      facilities: "Exceptional",
      recruitment: "Extensive",
      strategy:
        "City's academy focuses on developing technically gifted players who can fit into the first team's possession-based style. The pathway to the first team exists but is challenging due to the quality of the senior squad.",
      tips: [
        "Focus on loaning promising players to Championship or lower Premier League clubs",
        "Prioritize technical attributes in youth development",
        "Consider selling youth products with sell-on clauses",
        "Give youth chances in cup competitions",
      ],
      prospects: [
        {
          name: "James Wilson",
          age: 17,
          position: "AMC",
          potential: "Could develop into a world-class playmaker with the right training.",
        },
        {
          name: "Thomas Richards",
          age: 16,
          position: "ST",
          potential: "Has the physical attributes to become a complete forward.",
        },
        {
          name: "Omar Salah",
          age: 18,
          position: "DM",
          potential: "Technically gifted defensive midfielder with excellent vision.",
        },
      ],
    },
  },
  {
    id: "arsenal",
    name: "Arsenal",
    league: "Premier League",
    transferBudget: "£90M",
    wageBudget: "£2.2M / week",
    facilities: "Excellent",
    expectations: "Champions League Qualification",
    difficulty: "Medium",
    description:
      "A club with rich history looking to return to the pinnacle of English and European football. Good resources and young talent.",
    strengths: ["Young, talented squad", "Good financial backing", "Strong academy", "Attractive football philosophy"],
    weaknesses: [
      "Inconsistency in performances",
      "Need for strengthening in key positions",
      "Mental fragility in big games",
    ],
    opportunities: [
      "Build around young core for long-term success",
      "Develop academy talents",
      "Return to Champions League glory",
    ],
    threats: ["Fierce competition for top four", "Losing key players to bigger clubs", "Impatient fanbase"],
    tactics: [
      {
        name: "Arteta's Build-Up Play",
        description: "Patient possession with emphasis on building from the back and creating overloads in wide areas.",
        formation: "4-2-3-1",
        instructions: ["Play Out From The Back", "Overlap On Wings", "Work Ball Into Box", "Counter-Press"],
      },
      {
        name: "High-Intensity Press",
        description: "Aggressive pressing system to win the ball high up the pitch and attack quickly.",
        formation: "4-3-3",
        instructions: ["Extremely Urgent Pressing", "Higher Defensive Line", "Higher Tempo", "Counter"],
      },
    ],
    youthAcademy: {
      overview:
        "Arsenal has a proud tradition of developing young talent, with their Hale End academy producing numerous first-team players.",
      facilities: "Excellent",
      recruitment: "Strong",
      strategy:
        "Arsenal's youth development focuses on technical ability and tactical intelligence. The club has a clear pathway from academy to first team for exceptional talents.",
      tips: [
        "Give promising U23 players first-team exposure in cup competitions",
        "Loan developing players to Championship clubs for experience",
        "Focus on technical development in training",
        "Don't be afraid to promote youth to solve squad depth issues",
      ],
      prospects: [
        {
          name: "Ethan Edwards",
          age: 16,
          position: "AMR",
          potential: "Electric pace and dribbling ability with high technical ceiling.",
        },
        {
          name: "Leo Thompson",
          age: 17,
          position: "CB",
          potential: "Composed ball-playing defender with leadership qualities.",
        },
        {
          name: "Malik Rahman",
          age: 18,
          position: "CM",
          potential: "Complete midfielder with excellent passing range and vision.",
        },
      ],
    },
  },
  {
    id: "brentford",
    name: "Brentford",
    league: "Premier League",
    transferBudget: "£25M",
    wageBudget: "£800K / week",
    facilities: "Good",
    expectations: "Avoid Relegation",
    difficulty: "Hard",
    description: "A club with an innovative data-driven approach to recruitment. Limited resources but smart strategy.",
    strengths: [
      "Excellent recruitment model",
      "Strong team cohesion",
      "Innovative use of data analytics",
      "Sensible wage structure",
    ],
    weaknesses: [
      "Limited financial resources",
      "Smaller stadium and revenue streams",
      "Difficulty attracting top talent",
    ],
    opportunities: [
      "Establish as Premier League regulars",
      "Continue smart recruitment to find undervalued players",
      "Develop and sell players for profit",
    ],
    threats: [
      "Bigger clubs poaching best players and staff",
      "Relegation would be financially damaging",
      "Competing with wealthier clubs",
    ],
    tactics: [
      {
        name: "Pragmatic Counter-Attack",
        description: "Solid defensive shape with quick transitions and direct attacking play.",
        formation: "3-5-2",
        instructions: ["Counter Attack", "More Direct Passing", "Be More Disciplined", "Mixed Crossing"],
      },
      {
        name: "High-Energy Press",
        description: "Aggressive pressing to force turnovers in dangerous areas.",
        formation: "4-3-3",
        instructions: ["Higher Pressing Intensity", "Counter", "Early Crosses", "Prevent Short GK Distribution"],
      },
    ],
    youthAcademy: {
      overview:
        "Brentford has taken an unconventional approach, focusing on their B team rather than traditional academy structures.",
      facilities: "Adequate",
      recruitment: "Targeted",
      strategy:
        "Brentford focuses on recruiting released academy players from bigger clubs and developing them, as well as finding hidden gems abroad.",
      tips: [
        "Look for players released from top academies",
        "Focus on physical development alongside technical skills",
        "Target young players from Scandinavian leagues",
        "Develop players with sell-on potential",
      ],
      prospects: [
        {
          name: "Kevin Jensen",
          age: 19,
          position: "LB",
          potential: "Athletic full-back with modern attacking capabilities.",
        },
        {
          name: "Jamal Williams",
          age: 18,
          position: "ST",
          potential: "Clinical finisher with good movement and link-up play.",
        },
        {
          name: "Felix Andersen",
          age: 17,
          position: "CM",
          potential: "Technically sound midfielder with excellent work rate.",
        },
      ],
    },
  },
  {
    id: "ajax",
    name: "Ajax",
    league: "Eredivisie",
    transferBudget: "£30M",
    wageBudget: "£650K / week",
    facilities: "Excellent",
    expectations: "Win League Title",
    difficulty: "Medium",
    description:
      "A club with a legendary youth academy and commitment to attacking football. Develop and sell stars to bigger leagues.",
    strengths: [
      "World-famous youth academy",
      "Strong footballing philosophy",
      "Dominant in domestic league",
      "Good European reputation",
    ],
    weaknesses: [
      "Difficulty keeping top talents",
      "Financial gap to top European clubs",
      "Expectations to win domestically while developing youth",
    ],
    opportunities: [
      "Develop and sell players for huge profits",
      "Champions League progression",
      "Build long-term sustainable success",
    ],
    threats: [
      "Bigger clubs constantly poaching best players and staff",
      "Increasing competition in Eredivisie",
      "Financial disparity with elite European clubs",
    ],
    tactics: [
      {
        name: "Total Football Modernized",
        description: "Fluid, possession-based approach with positional rotations and high pressing.",
        formation: "4-3-3",
        instructions: ["Play Out From The Back", "Shorter Passing", "Work Ball Into Box", "Extremely Urgent Pressing"],
      },
      {
        name: "Wing Play",
        description: "Utilize pace and skill on the wings to create crossing opportunities.",
        formation: "4-2-3-1 Wide",
        instructions: ["Focus Play Down Wings", "Higher Tempo", "Early Crosses", "Counter-Press"],
      },
    ],
    youthAcademy: {
      overview: "Ajax's academy is legendary, having produced countless world-class players throughout its history.",
      facilities: "World Class",
      recruitment: "Excellent",
      strategy:
        "Ajax's youth development is centered around technical excellence, tactical intelligence, and the club's attacking philosophy.",
      tips: [
        "Promote youth team players to first team regularly",
        "Focus on technical attributes in training",
        "Give young players European experience",
        "Accept that developing and selling is the business model",
      ],
      prospects: [
        {
          name: "Johan van der Berg",
          age: 16,
          position: "AMC",
          potential: "Creative playmaker with exceptional technical ability.",
        },
        {
          name: "Lucas de Jong",
          age: 17,
          position: "CB",
          potential: "Ball-playing defender with excellent reading of the game.",
        },
        {
          name: "Ibrahim Diallo",
          age: 18,
          position: "RW",
          potential: "Explosive winger with end product and dribbling skills.",
        },
      ],
    },
  },
  {
    id: "milan",
    name: "AC Milan",
    league: "Serie A",
    transferBudget: "£50M",
    wageBudget: "£1.8M / week",
    facilities: "Excellent",
    expectations: "Champions League Qualification",
    difficulty: "Medium",
    description:
      "A historic giant of European football looking to return to former glories. Good mix of experience and youth.",
    strengths: [
      "Strong brand and history",
      "Good mix of experience and youth",
      "Tactical flexibility",
      "Passionate fanbase",
    ],
    weaknesses: [
      "Financial constraints compared to European elite",
      "Inconsistent performances",
      "Aging players in key positions",
    ],
    opportunities: [
      "Return to Champions League prominence",
      "Develop young talents into stars",
      "Capitalize on Serie A's tactical reputation",
    ],
    threats: [
      "Domestic competition from Juventus, Inter, and others",
      "Financial gap to Premier League clubs",
      "Losing key players to wealthier teams",
    ],
    tactics: [
      {
        name: "Italian Pragmatism",
        description: "Solid defensive structure with quick transitions and clinical finishing.",
        formation: "4-2-3-1",
        instructions: ["Counter Attack", "Be More Disciplined", "More Direct Passing", "Regroup When Possession Lost"],
      },
      {
        name: "Modern Possession",
        description: "Patient build-up play with focus on controlling the tempo of the game.",
        formation: "4-3-3 DM Wide",
        instructions: ["Shorter Passing", "Play Out From The Back", "Lower Tempo", "Work Ball Into Box"],
      },
    ],
    youthAcademy: {
      overview:
        "AC Milan has a proud tradition of developing talent, though their academy has had mixed results in recent years.",
      facilities: "Very Good",
      recruitment: "Strong",
      strategy:
        "Milan's youth development balances technical skills with tactical understanding, emphasizing the importance of positional awareness and game intelligence.",
      tips: [
        "Look to Serie B and C for young Italian talents",
        "Focus on tactical development alongside technical skills",
        "Loan promising players to mid-table Serie A clubs",
        "Emphasize mental attributes in training",
      ],
      prospects: [
        {
          name: "Marco Bianchi",
          age: 17,
          position: "DM",
          potential: "Composed defensive midfielder with excellent positioning.",
        },
        {
          name: "Alessandro Romano",
          age: 16,
          position: "AMC",
          potential: "Creative number 10 with flair and vision.",
        },
        {
          name: "Davide Esposito",
          age: 18,
          position: "CB",
          potential: "Commanding center-back with leadership qualities.",
        },
      ],
    },
  },
  {
    id: "dortmund",
    name: "Borussia Dortmund",
    league: "Bundesliga",
    transferBudget: "£60M",
    wageBudget: "£1.5M / week",
    facilities: "Excellent",
    expectations: "Champions League Qualification",
    difficulty: "Medium",
    description:
      "Known for developing young talents and playing exciting attacking football. Challenge is competing with Bayern Munich's dominance.",
    strengths: [
      "Excellent youth recruitment and development",
      "Attacking football philosophy",
      "Strong scouting network",
      "Passionate fanbase and atmosphere",
    ],
    weaknesses: [
      "Difficulty keeping star players",
      "Financial gap to Bayern Munich",
      "Inconsistent defensive performances",
    ],
    opportunities: [
      "Develop and sell players for significant profit",
      "Challenge for Bundesliga title",
      "Deep Champions League runs",
    ],
    threats: [
      "Bayern Munich's domestic dominance",
      "Bigger clubs poaching best talents",
      "Rising Bundesliga competition",
    ],
    tactics: [
      {
        name: "High-Intensity Gegenpressing",
        description: "Aggressive pressing system to win the ball high up the pitch and attack directly.",
        formation: "4-2-3-1",
        instructions: ["Counter-Press", "Extremely Urgent Pressing", "Higher Tempo", "Work Ball Into Box"],
      },
      {
        name: "Rapid Transitions",
        description: "Quick vertical passing to exploit space behind opposition defenses.",
        formation: "4-3-3",
        instructions: ["Counter", "More Direct Passing", "Higher Tempo", "Run At Defense"],
      },
    ],
    youthAcademy: {
      overview:
        "Borussia Dortmund has established itself as one of the best clubs in Europe for developing young talent.",
      facilities: "Excellent",
      recruitment: "World Class",
      strategy:
        "Dortmund focuses on identifying young talents with high potential and providing them with first-team opportunities at an early age.",
      tips: [
        "Scout extensively in emerging markets like Eastern Europe and Africa",
        "Provide clear pathway to first team for top prospects",
        "Focus on technical and physical development",
        "Accept the 'develop and sell' model as part of club identity",
      ],
      prospects: [
        {
          name: "Felix Müller",
          age: 17,
          position: "AMR",
          potential: "Explosive winger with excellent dribbling and finishing.",
        },
        {
          name: "Tobias Schmidt",
          age: 16,
          position: "CM",
          potential: "Complete midfielder with technical ability and physical presence.",
        },
        {
          name: "Kofi Mensah",
          age: 18,
          position: "ST",
          potential: "Powerful striker with pace and clinical finishing.",
        },
      ],
    },
  },
]

export const players = [
  {
    id: "player-1",
    name: "Kevin De Bruyne",
    position: "AMC",
    age: 31,
    nationality: "Belgium",
    team: "Manchester City",
    teamId: "manchester-city",
    value: "£85M",
    wage: "£350K p/w",
    rating: "91",
    role: "Advanced Playmaker",
    attributes: {
      Passing: 20,
      Vision: 19,
      Technique: 18,
      Decisions: 17,
      Teamwork: 16,
      Stamina: 15,
    },
  },
  {
    id: "player-2",
    name: "Erling Haaland",
    position: "ST",
    age: 22,
    nationality: "Norway",
    team: "Manchester City",
    teamId: "manchester-city",
    value: "£150M",
    wage: "£375K p/w",
    rating: "94",
    role: "Advanced Forward",
    attributes: {
      Finishing: 20,
      Pace: 18,
      Strength: 19,
      Composure: 17,
      OffTheBall: 18,
      Heading: 16,
    },
  },
  {
    id: "player-3",
    name: "Bukayo Saka",
    position: "AMR",
    age: 21,
    nationality: "England",
    team: "Arsenal",
    teamId: "arsenal",
    value: "£95M",
    wage: "£195K p/w",
    rating: "88",
    role: "Inside Forward",
    attributes: {
      Dribbling: 17,
      Technique: 16,
      Pace: 16,
      WorkRate: 17,
      Decisions: 15,
      Crossing: 16,
    },
  },
  {
    id: "player-4",
    name: "Martin Ødegaard",
    position: "AMC",
    age: 24,
    nationality: "Norway",
    team: "Arsenal",
    teamId: "arsenal",
    value: "£80M",
    wage: "£200K p/w",
    rating: "87",
    role: "Advanced Playmaker",
    attributes: {
      Vision: 18,
      Passing: 17,
      Technique: 17,
      FirstTouch: 16,
      Decisions: 16,
      Flair: 15,
    },
  },
  {
    id: "player-5",
    name: "Ivan Toney",
    position: "ST",
    age: 27,
    nationality: "England",
    team: "Brentford",
    teamId: "brentford",
    value: "£45M",
    wage: "£80K p/w",
    rating: "83",
    role: "Complete Forward",
    attributes: {
      Finishing: 16,
      PenaltyTaking: 19,
      Strength: 16,
      Heading: 15,
      WorkRate: 15,
      Teamwork: 14,
    },
  },
  {
    id: "player-6",
    name: "Brian Mbeumo",
    position: "AMR",
    age: 23,
    nationality: "Cameroon",
    team: "Brentford",
    teamId: "brentford",
    value: "£30M",
    wage: "£60K p/w",
    rating: "80",
    role: "Inside Forward",
    attributes: {
      Pace: 15,
      Dribbling: 14,
      Finishing: 14,
      WorkRate: 15,
      OffTheBall: 14,
      Technique: 13,
    },
  },
  {
    id: "player-7",
    name: "Jurriën Timber",
    position: "CB",
    age: 22,
    nationality: "Netherlands",
    team: "Ajax",
    teamId: "ajax",
    value: "£40M",
    wage: "£45K p/w",
    rating: "82",
    role: "Ball Playing Defender",
    attributes: {
      Tackling: 15,
      Passing: 15,
      Composure: 16,
      Positioning: 15,
      Pace: 14,
      Technique: 14,
    },
  },
  {
    id: "player-8",
    name: "Kenneth Taylor",
    position: "CM",
    age: 21,
    nationality: "Netherlands",
    team: "Ajax",
    teamId: "ajax",
    value: "£25M",
    wage: "£30K p/w",
    rating: "79",
    role: "Box-to-Box Midfielder",
    attributes: {
      Passing: 15,
      Technique: 15,
      WorkRate: 16,
      Stamina: 15,
      Teamwork: 14,
      FirstTouch: 14,
    },
  },
  {
    id: "player-9",
    name: "Rafael Leão",
    position: "AML",
    age: 24,
    nationality: "Portugal",
    team: "AC Milan",
    teamId: "milan",
    value: "£75M",
    wage: "£165K p/w",
    rating: "86",
    role: "Inside Forward",
    attributes: {
      Pace: 18,
      Dribbling: 17,
      Technique: 16,
      Flair: 16,
      Acceleration: 17,
      Finishing: 15,
    },
  },
  {
    id: "player-10",
    name: "Sandro Tonali",
    position: "DM",
    age: 23,
    nationality: "Italy",
    team: "AC Milan",
    teamId: "milan",
    value: "£55M",
    wage: "£110K p/w",
    rating: "84",
    role: "Deep-Lying Playmaker",
    attributes: {
      Passing: 16,
      Tackling: 15,
      Vision: 15,
      Positioning: 15,
      WorkRate: 16,
      Technique: 15,
    },
  },
  {
    id: "player-11",
    name: "Jude Bellingham",
    position: "CM",
    age: 20,
    nationality: "England",
    team: "Borussia Dortmund",
    teamId: "dortmund",
    value: "£120M",
    wage: "£180K p/w",
    rating: "89",
    role: "Box-to-Box Midfielder",
    attributes: {
      Passing: 17,
      Technique: 17,
      WorkRate: 18,
      Tackling: 15,
      Vision: 16,
      Decisions: 16,
    },
  },
  {
    id: "player-12",
    name: "Youssoufa Moukoko",
    position: "ST",
    age: 18,
    nationality: "Germany",
    team: "Borussia Dortmund",
    teamId: "dortmund",
    value: "£35M",
    wage: "£45K p/w",
    rating: "78",
    role: "Advanced Forward",
    attributes: {
      Finishing: 15,
      Pace: 16,
      Technique: 14,
      Dribbling: 15,
      Composure: 13,
      OffTheBall: 15,
    },
  },
]
